/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class chenyue_arfyp_common_freetype_FreetypeJNI */

#ifndef _Included_chenyue_arfyp_common_freetype_FreetypeJNI
#define _Included_chenyue_arfyp_common_freetype_FreetypeJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     chenyue_arfyp_common_freetype_FreetypeJNI
 * Method:    getFontTexFromC
 * Signature: ()[Lchenyue/arfyp/common/freetype/FreetypeJNI;
 */
JNIEXPORT jobjectArray JNICALL Java_chenyue_arfyp_common_freetype_FreetypeJNI_getFontTexFromC
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
